# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hDpq7F5l747GtpGlK1QQJC1b_B2czHEq
"""

!pip install mlflow

!pip install mlflow dagshub

import tensorflow as tf
from tensorflow.keras import layers, models
import mlflow
import dagshub
import mlflow.tensorflow


(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.cifar10.load_data()
train_images, test_images = train_images / 255.0, test_images / 255.0

mlflow.set_experiment("CNN_CIFAR10")
mlflow.tensorflow.autolog()