# -*- coding: utf-8 -*-
"""kod.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hDpq7F5l747GtpGlK1QQJC1b_B2czHEq
"""

!pip install mlflow dagshub --ignore-installed blinker

import tensorflow as tf
from tensorflow.keras import layers, models
import mlflow
import dagshub
import mlflow.tensorflow


(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.cifar10.load_data()
train_images, test_images = train_images / 255.0, test_images / 255.0

dagshub.init(repo_owner='OlivierArthur', repo_name='CNN_cifar10', mlflow=True)
mlflow.set_experiment("CNN_CIFAR10")
mlflow.tensorflow.autolog()

experiments = [
    {
        "name": "Eksperyment_1_prosty",
        "layers": [
            layers.Conv2D(32, (3, 3), activation='relu',padding='same', input_shape=(32, 32, 3)),
            layers.MaxPooling2D((2, 2)),
            layers.Flatten(),
            layers.Dense(64, activation='relu'),
            layers.Dense(10)
        ]
    },
    {
        "name": "Eksperyment_2_glebszy",
        "layers": [
            layers.Conv2D(32, (3, 3), activation='relu',padding='same', input_shape=(32, 32, 3)),
            layers.MaxPooling2D((2, 2)),
            layers.Conv2D(64, (3, 3), activation='relu',padding='same'),
            layers.MaxPooling2D((2, 2)),
            layers.Conv2D(64, (3, 3), activation='relu',padding='same'),
            layers.Flatten(),
            layers.Dense(128, activation='relu'),
            layers.Dense(10)
        ]
    },
    {
        "name": "Eksperyment_3_Dropout",
        "layers": [
            layers.Conv2D(32, (3, 3), activation='relu',padding='same', input_shape=(32, 32, 3)),
            layers.MaxPooling2D((2, 2)),
            layers.Dropout(0.2),
            layers.Conv2D(64, (3, 3), activation='relu',padding='same'),
            layers.MaxPooling2D((2, 2)),
            layers.Flatten(),
            layers.Dense(64, activation='relu'),
            layers.Dense(10)
        ]
    }
]

for exp in experiments:
  with mlflow.start_run(run_name=exp['name']):
    model = models.Sequential(exp['layers'])

    model.compile(optimizer='adam',
                  loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                  metrics=['accuracy'])
    model.fit(train_images, train_labels, epochs=10,
              validation_data=(test_images, test_labels), verbose=1)

!pip install tensorboard